name: Build and Push Frontend Docker Image

on:
  workflow_run:
    workflows: ["Test Frontend"]
    types:
      - completed
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prd
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./Frontend
        target: prd
        build-args: |
          "PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}"
          "API_URL=${{ secrets.API_URL }}"
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/organize-this-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/organize-this-frontend:${{ github.run_number }}
