name: Test Frontend
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm ci .
        working-directory: Frontend

      # - name: Setup Playwright
      #   run: npx playwright install
      #   working-directory: Frontend

      - name: Test with npm
        run: npm run test:unit
        working-directory: Frontend
